# Generated by Django 5.2 on 2025-05-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_currency_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('SSLCommerz', 'SSLCommerz')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
